### PR TITLE
fixed config buttons on actor and npcs

### PR DESCRIPTION
**Pull request by awitteck**

### CODE REVIEW

**Comment by awitteck** [comment]
fixed on startship sheet as well

**Comment by supervj** [comment]
@awitteck We compile the .less into the .css, any chance you can make the changes to the .less so the .css isn't overwritten during the recompile?  Also, I was trying to keep the original sheet intact so we can see it's functionality, and chance you can create additional lines in the css/less instead of overwriting them so that both sheets are functional?

**Comment by awitteck** [comment]
Sorry for that... i did not know that. 

Sure i will take a look into the less. Never worked with it but i'll try getting into it.

**Comment by supervj** [comment]
No worries, thanks for the help!

**Pull request merged**
